# These are living organisms 
## best practice is that service comes first 
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
  # remember you still have to expose the service using minikube service backend 
--- #must have three dashes to show to yaml a new object is created. 
# now we can have any many service definitions  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: second-app
    #   tier: backend
    matchExpressions: 
      # more configuration options like matchLabels, but stronger. 
      # list of expresses that it matches again 
      - {key: app, operators: In, values: [second-app, first-app]} # still matching on labels
      # more details on these and operators can be found here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#objectmeta-v1-meta  
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: listentoripley/kube-first-app
        # - name: ...
        #   image: ...

