version: "3.8"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
      # # - MONGODB_USERNAME: natalie or 
      # - MONGO_INIT_ROOT_USERNAME=natalie
      # - MONGO_INIT_ROOT_PASSWORD:secret 
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net 
  # backend:
    
  # frontend:
volumes: 
  data: 
