apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector: 
    #select the pod created in deployment
    app: story  # will pull pod from deployment 
  ports: 
    -protocol: "TCP"
    port: 80
    targetPort: 3000 # port inside of the container